/// Generated by Claude, todo: code review
/// Minimal D bindings for the QuickJS JavaScript engine.
/// Only the functions required for evaluating YouTube's base.js are bound.
/// Targets: https://github.com/quickjs-ng/quickjs (non-NAN_BOXING build)
module quickjs;

import std.conv : to;
import std.string : toStringz;

// ── Opaque types ──────────────────────────────────────────────────────

struct JSRuntime;
struct JSContext;

// ── JSValue ───────────────────────────────────────────────────────────

union JSValueUnion
{
    int    int32;
    double float64;
    void*  ptr;
    long   short_big_int;
}

struct JSValue
{
    JSValueUnion u;
    long tag; // int64_t
}

// ── JS_TAG constants ──────────────────────────────────────────────────

enum : int
{
    JS_TAG_FIRST             = -9,
    JS_TAG_BIG_INT           = -9,
    JS_TAG_SYMBOL            = -8,
    JS_TAG_STRING            = -7,
    JS_TAG_STRING_ROPE       = -6,
    JS_TAG_MODULE            = -3,
    JS_TAG_FUNCTION_BYTECODE = -2,
    JS_TAG_OBJECT            = -1,

    JS_TAG_INT               =  0,
    JS_TAG_BOOL              =  1,
    JS_TAG_NULL              =  2,
    JS_TAG_UNDEFINED         =  3,
    JS_TAG_UNINITIALIZED     =  4,
    JS_TAG_CATCH_OFFSET      =  5,
    JS_TAG_EXCEPTION         =  6,
    JS_TAG_SHORT_BIG_INT     =  7,
    JS_TAG_FLOAT64           =  8,
}

// ── Eval flags ────────────────────────────────────────────────────────

enum
{
    JS_EVAL_TYPE_GLOBAL     = 0 << 0,
    JS_EVAL_TYPE_MODULE     = 1 << 0,
    JS_EVAL_FLAG_STRICT     = 1 << 3,
    JS_EVAL_FLAG_COMPILE_ONLY = 1 << 5,
}

// ── Predefined values ─────────────────────────────────────────────────

enum JSValue JS_UNDEFINED = JSValue(JSValueUnion(0), JS_TAG_UNDEFINED);
enum JSValue JS_NULL      = JSValue(JSValueUnion(0), JS_TAG_NULL);
enum JSValue JS_EXCEPTION = JSValue(JSValueUnion(0), JS_TAG_EXCEPTION);

// ── Inline helpers ───────────────────────────────────────────────────

bool JS_IsException(JSValue v) pure nothrow @nogc
{
    return cast(int) v.tag == JS_TAG_EXCEPTION;
}

/// Convenience wrapper matching the C static-inline JS_ToCString.
const(char)* JS_ToCString(JSContext* ctx, JSValue val)
{
    return JS_ToCStringLen2(ctx, null, val, 0);
}

// ── extern(C) functions from libquickjs ──────────────────────────────

extern (C) nothrow @nogc
{
    // Runtime
    JSRuntime* JS_NewRuntime();
    void       JS_FreeRuntime(JSRuntime* rt);

    // Context
    JSContext* JS_NewContext(JSRuntime* rt);
    void       JS_FreeContext(JSContext* ctx);

    // Evaluation
    JSValue JS_Eval(JSContext* ctx, const(char)* input, size_t input_len,
                    const(char)* filename, int eval_flags);

    // Global object & properties
    JSValue JS_GetGlobalObject(JSContext* ctx);
    JSValue JS_GetPropertyStr(JSContext* ctx, JSValue this_obj,
                              const(char)* prop);

    // String conversion
    const(char)* JS_ToCStringLen2(JSContext* ctx, size_t* plen,
                                  JSValue val1, int cesu8);
    void JS_FreeCString(JSContext* ctx, const(char)* ptr);

    // Exception handling
    JSValue JS_GetException(JSContext* ctx);

    // Memory management (exported directly in QuickJS-NG)
    void JS_FreeValue(JSContext* ctx, JSValue v);
}

// ── High-level helpers ────────────────────────────────────────────────
// Convenience wrappers that mirror the Duktape usage patterns in
// challenges.d so the migration is straightforward.

/// Evaluate a JavaScript string and return the string value of a global
/// variable, or throw on error.  This is the QuickJS equivalent of:
///
///     duk_peval_string(ctx, js);
///     duk_get_global_string(ctx, name);
///     duk_get_string(ctx, -1);
///
string evalJS(string javascript, string globalName)
{
    JSRuntime* rt = JS_NewRuntime();
    if (rt is null)
        throw new Exception("QuickJS: failed to create runtime");

    scope(exit) JS_FreeRuntime(rt);

    JSContext* ctx = JS_NewContext(rt);
    if (ctx is null)
        throw new Exception("QuickJS: failed to create context");

    scope(exit) JS_FreeContext(ctx);

    // Evaluate
    JSValue ret = JS_Eval(ctx, javascript.toStringz(), javascript.length,
                          "<input>".ptr, JS_EVAL_TYPE_GLOBAL);

    if (JS_IsException(ret))
    {
        JSValue exc = JS_GetException(ctx);
        const(char)* msg = JS_ToCString(ctx, exc);
        string err = msg !is null ? msg.to!string : "unknown error";
        if (msg !is null) JS_FreeCString(ctx, msg);
        JS_FreeValue(ctx, exc);
        throw new Exception(err);
    }
    JS_FreeValue(ctx, ret);

    // Read the global variable
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue val    = JS_GetPropertyStr(ctx, global, globalName.toStringz());

    const(char)* cstr = JS_ToCString(ctx, val);
    string result = cstr !is null ? cstr.to!string : "";
    if (cstr !is null) JS_FreeCString(ctx, cstr);

    JS_FreeValue(ctx, val);
    JS_FreeValue(ctx, global);

    return result;
}

