name: Release

on: [push]

jobs:
  create_release_job:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: New release of youtube-d ${{ github.ref_name }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md

  upload_release_assets_job:
    strategy:
      matrix:
        version: [ { os: ubuntu-20.04, suffix: x86_64, extension: '' }, { os: windows-latest, suffix: win64, extension: '.exe' }]

    runs-on: ${{ matrix.version.os }}
    needs: create_release_job
    steps:
      - uses: actions/checkout@v1

      - uses: dlang-community/setup-dlang@v1
        name: Install LDC
        with:
          compiler: ldc-latest

      - name: Build release
        run: dub build -b release --compiler=ldc2

      - name: Prepare assets (Windows)
        if: matrix.version.suffix == 'win64'
        run: |
          curl -LO https://downloads.dlang.org/other/libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          tar -xf libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          xcopy dmd2\windows\bin64\libcurl.dll .
          rm -r dmd2
          rm libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          tar cavf youtube-d-${{ matrix.version.suffix }}.zip youtube-d${{ matrix.version.extension }} libcurl.dll

      - name: Prepare assets (Linux)
        if: matrix.version.suffix == 'x86_64'
        run: |
          zip youtube-d-${{ matrix.version.suffix }}.zip youtube-d${{ matrix.version.extension }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release_job.outputs.upload_url }}
          asset_path: ./youtube-d-${{ matrix.version.suffix }}.zip
          asset_name: youtube-d-${{ matrix.version.suffix }}
          asset_content_type: application/zip

