name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        version: [ { os: ubuntu-22.04, suffix: x86_64, extension: '' }, { os: windows-latest, suffix: win64, extension: '.exe' }, { os: macos-latest, suffix: macos, extension: '' }]
    runs-on: ${{ matrix.version.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: dlang-community/setup-dlang@v1
        name: Install LDC
        with:
          compiler: ldc-1.40.0

      - name: Build release
        run: dub build -b release --compiler=ldc2

      - name: Prepare assets (Windows)
        if: matrix.version.suffix == 'win64'
        run: |
          curl -LO https://downloads.dlang.org/other/libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          tar -xf libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          xcopy dmd2\windows\bin64\libcurl.dll .
          rm -r dmd2
          rm libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
          tar cavf youtube-d-${{ matrix.version.suffix }}.zip youtube-d${{ matrix.version.extension }} libcurl.dll

      - name: Prepare assets (Linux or MacOS)
        if: matrix.version.suffix == 'x86_64' || matrix.version.suffix == 'macos'
        run: |
          zip youtube-d-${{ matrix.version.suffix }}.zip youtube-d${{ matrix.version.extension }}

      - name: Store build as artifact
        uses: actions/upload-artifact@v4
        with:
          path: youtube-d-${{ matrix.version.suffix }}.zip
          name: youtube-d-${{ matrix.version.suffix }}.zip

  release:
    runs-on: 'ubuntu-22.04'
    needs: build
    steps:
      - uses: actions/checkout@v1

      - name: Downloads builds from previous job
        uses: actions/download-artifact@v5
        with:
          pattern: youtube-d-*.zip
          path: .
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: New release of youtube-d ${{ github.ref_name }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
          files: |
            youtube-d-x86_64.zip
            youtube-d-win64.zip
            youtube-d-macos.zip
