name: Unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: mihails-strasuns/setup-dlang@v1
      name: Install DMD

    - name: Build
      run: dub build

    - name: Unit tests
      run: dub test --coverage

