name: Unit tests

on:
  push:
    tags:
      - 'v0.0.1'

jobs:
  test:
    strategy:
      matrix:
        os: [ { name: ubuntu-20.04, command: sh tests.sh } , { name: windows-latest, command: powershell.exe -file tests.ps1 }]

    runs-on: ${{ matrix.os.name }}
    steps:
    - uses: actions/checkout@v1

    - uses: mihails-strasuns/setup-dlang@v1
      name: Install DMD

    - name: Build
      run: dub build

    - name: Unit tests
      run: dub test --coverage

    - name: e2e tests
      run: ${{ matrix.os.command }}


