name: Unit tests

on: [push]

jobs:
  unit_test:
    strategy:
      matrix:
        os: [ { name: windows-latest, extension: '.exe' } ]

    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v1

    - uses: dlang-community/setup-dlang@v1
      name: Install LDC
      with:
        compiler: ldc-1.40.0

    - name: Build
      run: dub build

    - name: Unit tests
      run: dub test --coverage

    - uses: actions/cache/save@v3
      id: cache
      with:
        path: youtube-d${{ matrix.os.extension }}
        key: youtube-d-${{ matrix.os.name }}

  console_test:
    strategy:
      matrix:
        os: [ { name: ubuntu-22.04, command: sh tests/tests.sh, extension: '' } , { name: windows-latest, command: powershell.exe -file tests\tests.ps1, extension: '.exe' }, { name: macos-latest, command: sh tests/tests-macos.sh, extension: '' }]

    runs-on: ${{ matrix.os.name }}
    needs: unit_test
    if: false

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache/restore@v3
      id: cache
      with:
        path: youtube-d${{ matrix.os.extension }}
        key: youtube-d-${{ matrix.os.name }}

    - name: Download libcurl.dll
      if: matrix.os.name == 'windows-latest'
      run: |
        curl -LO https://downloads.dlang.org/other/libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
        tar -xf libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
        xcopy dmd2\windows\bin64\libcurl.dll .

    - name: e2e tests
      run: ${{ matrix.os.command }}

