name: Unit tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ { name: ubuntu-20.04, command: sh tests.sh, extension: '' } , { name: windows-2019, command: powershell.exe -file tests.ps1, extension: '.exe' }]

    runs-on: ${{ matrix.os.name }}
    steps:
    - uses: actions/checkout@v1

    - uses: mihails-strasuns/setup-dlang@v1
      name: Install DMD

    - name: Build
      run: dub build

    - name: Unit tests
      run: dub test --coverage

    - name: e2e tests
      run: ${{ matrix.os.command }}

    - uses: actions/upload-artifact@v3
      with:
        name: youtube-d-${{ matrix.os.name }}
        path: youtube-d${{ matrix.os.extension }}
