name: Unit tests

on: [push]

jobs:
  unit_test:
    strategy:
      matrix:
        #os: [ { name: ubuntu-20.04, extension: '' } , { name: windows-2019, extension: '.exe' }]
        os: [ { name: windows-2019, extension: '.exe' } ]

    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v1

    - uses: mihails-strasuns/setup-dlang@v1
      name: Install DMD

    - name: Build
      run: dub build

    - name: Unit tests
      run: dub test --coverage

    - uses: actions/upload-artifact@v3
      with:
        name: youtube-d-${{ matrix.os.name }}
        path: youtube-d${{ matrix.os.extension }}

  console_test:
    strategy:
      matrix:
        #os: [ { name: ubuntu-20.04, command: sh tests.sh, extension: '' } , { name: windows-2019, command: powershell.exe -file tests.ps1, extension: '.exe' }]
        os: [ { name: windows-2019, command: powershell.exe -file tests.ps1, extension: '.exe' } ]

    runs-on: ${{ matrix.os.name }}
    needs: unit_test

    steps:
    - uses: actions/checkout@v1

    - run: |
        curl -LO https://downloads.dlang.org/other/libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
        tar -xf libcurl-7.68.0-WinSSL-zlib-x86-x64.zip
        dir
        xcopy dmd2\windows\bin64\libcurl.dll .

    - uses: actions/download-artifact@v3
      with:
        name: youtube-d-${{ matrix.os.name }}

    - name: e2e tests
      run: ${{ matrix.os.command }}

